### ISSUE TITLE
Dependency checking broken on 1.19.3 paper

### ISSUE THREAD

**Issue by emeraldtip** [TheBlackEntity/PlugMan#11]
Idk if this is a known issue yet, but if I try to reload a plugin I get:
```
[14:59:09 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/PotatoWarsPlugin.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [FastAsyncWorldEdit]. Please download and install these plugins to run 'PotatoWars'.
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:80) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:63) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:121) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:367) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-448]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:59:09 WARN]: org.bukkit.plugin.InvalidPluginException: Plugin didn't load any plugin providers?
[14:59:09 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.lambda$loadPlugin$1(PaperPluginInstanceManager.java:127)
[14:59:09 WARN]:        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[14:59:09 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:127)
[14:59:09 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82)
[14:59:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406)
[14:59:09 WARN]:        at PlugManX.jar//com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:367)
[14:59:09 WARN]:        at PlugManX.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116)
[14:59:09 WARN]:        at PlugManX.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98)
[14:59:09 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:59:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[14:59:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911)
[14:59:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[14:59:09 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[14:59:09 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:316)
[14:59:09 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:300)
[14:59:09 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[14:59:09 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[14:59:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[14:59:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:59:09 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:59:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:59:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:59:09 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[14:59:09 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:59:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:59:09 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[14:59:09 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[14:59:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:59:09 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[14:59:09 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[14:59:09 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:59:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by emeraldtip** [comment]
Nvm I just read the PR
