### ISSUE TITLE
Plugins with dependencies fail to load even with dependencies present

### ISSUE THREAD

**Issue by raffel080108** [TheBlackEntity/PlugMan#15]
When trying to load a plugin which needs has (a) dependency(s) the load will fail with an error stating that dependencies are missing. I have had this with several plugins now and in all cases the dependency plugins had been loaded beforehand using PlugmanX as well

**Comment by TheBlackEntity** [comment]
Hey!

Make sure you're using the very latest paper version.

This was a paper bug in older paper versions

**Comment by raffel080108** [comment]
Hi, my server is running the latest paper version
git-Paper-"a40e48f" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a40e48f)

**Comment by TheBlackEntity** [comment]
It works just fine for me.

Tested it on this version:
Paper version git-Paper-98 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a40e48f)

Which is the very latest version.

Can you give me more informations about your setup?

**Comment by TheBlackEntity** [comment]
Again, I tested it on the latest paper version, which works just fine.

Also, this is my java version:
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)


I tried loading GCore and CustomCommands  normally.

After that, I installed a paper plugin in case this messes things up and tried again.

I also tried loading WorldGuard after making it fail to load on start up.


I also noticed you listed FastAsyncWorldEdit twice, is it listed twice when using /plugins ?

**Comment by TheBlackEntity** [comment]
In case you tried *reloading* FAWE, that won't work

**Comment by raffel080108** [comment]
I am installing the plugins on disc and then loading them via command. Also I have not had this issue when using plugman a while ago, so I'm not even sure why it's happening now

An in-game version of the plugins command (still not sure why FAWE shows up twice)
![image](https://github.com/TheBlackEntity/PlugMan/assets/62069283/41553e5c-a0b6-42f5-9019-314d88f62a6b)
No plugins except for Gcore and CustomCommands were loaded using plugman, to my knowledge every other plugin on the server was loaded on server startup - (DisableSignEdit and Holograms were **un**loaded previously, not sure why they are even showing up there...

Here is also the console stacktrace
```
28.07 14:42:57 [Server] [ERROR] [LegacyPluginLoadingStrategy] Could not load 'plugins/CustomCommands.jar' in folder 'plugins'
28.07 14:42:57 [Server] [INFO] org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [GCore]. Please download and install these plugins to run 'CustomCommands'.
28.07 14:42:57 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.strategy.LegacyPluginLoadingStrategy.loadProviders(LegacyPluginLoadingStrategy.java:169) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:57) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:118) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
28.07 14:42:57 [Server] [INFO] at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:419) ~[PlugManX.jar:?]
28.07 14:42:57 [Server] [INFO] at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX.jar:?]
28.07 14:42:57 [Server] [INFO] at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
28.07 14:42:57 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
28.07 14:42:57 [Server] [INFO] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
28.07 14:42:57 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1006) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2299) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
28.07 14:42:57 [Server] [INFO] at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-"a40e48f"]
28.07 14:42:57 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
28.07 14:42:57 [Server] [WARN] org.bukkit.plugin.InvalidPluginException: Plugin didn't load any plugin providers?
28.07 14:42:57 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.lambda$loadPlugin$1(PaperPluginInstanceManager.java:124)
28.07 14:42:57 [Server] [WARN] at java.base/java.util.Optional.orElseThrow(Optional.java:403)
28.07 14:42:57 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:124)
28.07 14:42:57 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82)
28.07 14:42:57 [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406)
28.07 14:42:57 [Server] [WARN] at PlugManX.jar//com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:419)
28.07 14:42:57 [Server] [WARN] at PlugManX.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116)
28.07 14:42:57 [Server] [WARN] at PlugManX.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97)
28.07 14:42:57 [Server] [WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
28.07 14:42:57 [Server] [WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
28.07 14:42:57 [Server] [WARN] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1006)
28.07 14:42:57 [Server] [WARN] at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
28.07 14:42:57 [Server] [WARN] at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
28.07 14:42:57 [Server] [WARN] at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
28.07 14:42:57 [Server] [WARN] at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2299)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2259)
28.07 14:42:57 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
28.07 14:42:57 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
28.07 14:42:57 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
28.07 14:42:57 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
28.07 14:42:57 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
28.07 14:42:57 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1425)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
28.07 14:42:57 [Server] [WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
28.07 14:42:57 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by TheBlackEntity** [comment]
What version of PlugManX are you using?

**Comment by raffel080108** [comment]
Version 2.3.3

**Comment by TheBlackEntity** [comment]
Can I have your entire log via https://mclo.gs/ ?
